### ISSUE TITLE
kosmtik start but cant see nothing

### ISSUE THREAD

**Issue by randyhbh** [Joxit/docker-kosmtik#2]
Hi, first of all, great job, but I'm facing an error when running the dock container. I'll describe what I'm doing
- i pull the docker coupler image from docker dock `` `` dock / joxit / kosmtik```
- I have a local postgres installation with potgis and data from my data.osm.pbf file already imported.
- I create my `` `localconfig.js``` file and I define the following
(I.e.
exports.LocalConfig = function (localizer, project) {
    localizer.where ('Layer') if ({'Datasource.type': 'postgis'}). then ({
        'Datasource.dbname': 'gis',
        'Datasource.password': '',
        'Datasource.user': 'postgres',
        'Datasource.host': ''
    });
};
(I.e.
- Then I run the following command in console according to example
(I.e.
docker run -d \
    -p 6789: 6789
    -v / path / to / my / project: / opt / project \
    -and USER_ID = 1000 \
    joxit / kosmtik \
    kosmtik serves /opt/project/project.mml --host 0.0.0.0
(I.e.

and when I check my browser in the address http://127.0.0.1:6789 nothing comes out
what is the problem, I am doing something wrong, it is by the local database. Could help me

**Comment by Joxit** [comment]
Hi, thx :)

- In your localconfig: 
  - a dot is missing before if `localizer.where ('Layer').if ({'Datasource.type': 'postgis'}).`
  - Datasource.host value is missing. 
    - This will be read by kosmtik inside a docker, 127.0.0.1 will not work here. 
    - If your postgres is in another docker, you should use docker networks.
    - If the postgres is installed on your your computer, you should write your private IP address (like 192.168.x.x or 10.x.x.x)
  - `kosmtik serve` and not `kosmtik serves`

What is your output ? (with `docker logs `)
```
[Core] Loading config from /root/.config/kosmtik.yml
[Core] Loading plugin from ../plugins/base-exporters/index.js
[Core] Loading plugin from ../plugins/hash/index.js
[Core] Loading plugin from ../plugins/local-config/index.js
[Core] Loading plugin from ../plugins/datasource-loader/index.js
[Core] Loading plugin from kosmtik-tiles-export
[Core] Loading plugin from kosmtik-fetch-remote
[Core] Loading plugin from kosmtik-overlay
[Core] Loading plugin from kosmtik-deploy
[Core] Loading plugin from kosmtik-overpass-layer
[Core] Loading plugin from kosmtik-map-compare
[Core] Loading plugin from kosmtik-mapnik-reference
[Core] Loading plugin from kosmtik-osm-data-overlay
[Core] Loading plugin from kosmtik-mbtiles-export
[Core] Loading plugin from kosmtik-place-search
[Core] Loading plugin from kosmtik-geojson-overlay
[Core] Loading plugin from kosmtik-open-in-josm
[Core] Loading project from style.yml
[Core] PreviewServer started, you can browse http://0.0.0.0:6789
[Core] Creating metatiles cache dir tmp/project/meta
[Core] Deleting previous metatiles tmp/project/meta
[Local Config] Patched config from /opt/project/localconfig.js
[Fetch Remote] Done.
[Core] Generating Mapnik XML…
[Core] Using mapnik version 3.0.12
```

What do you see in http://127.0.0.1:6789 ? The komstik UI ? Or a white page with `Not Found: /opt/kosmtik/src/front/index.html` ?

**Comment by randyhbh** [comment]
The problem was like you said. 

> Datasource.host value is missing.
> This will be read by kosmtik inside a docker, 127.0.0.1 will not work here.
>     If your postgres is in another docker, you should use docker networks.
>     If the postgres is installed on your your computer, you should write your private IP address (like 192.168.x.x or 10.x.x.x)

I think you shoul consider add this to the README.md file for completitud. Regards

**Comment by Joxit** [comment]
Ok, thx for your feedback. 

I will add this in the README.md.
