### ISSUE TITLE
Font missing

### ISSUE THREAD

**Issue by randyhbh** [Joxit/docker-kosmtik#3]
Need upgrade the Docker file to include this fonts, possible solution
[https://github.com/gravitystorm/openstreetmap-carto/blob/master/INSTALL.md#installation-on-ubuntudebian](https://github.com/gravitystorm/openstreetmap-carto/blob/master/INSTALL.md#installation-on-ubuntudebian)
`placenames.mss:106:4 The font 'Noto Sans UI Regular, Noto Sans CJK JP Regular, Noto Sans Armenian Regular, Noto Sans Balinese Regular, Noto Sans Bamum Regular, Noto Sans Batak Regular, Noto Sans Bengali UI Regular, Noto Sans Buginese Regular, Noto Sans Buhid Regular, Noto Sans Canadian Aboriginal Regular, Noto Sans Cham Regular, Noto Sans Cherokee Regular, Noto Sans Coptic Regular, Noto Sans Devanagari UI Regular, Noto Sans Devanagari Regular, Noto Sans Ethiopic Regular, Noto Sans Georgian Regular, Noto Sans Gujarati UI Regular, Noto Sans Gujarati Regular, Noto Sans Gurmukhi UI Regular, Noto Sans Hanunoo Regular, Noto Sans Hebrew Regular, Noto Sans Javanese Regular, Noto Sans Kannada UI Regular, Noto Sans Kayah Li Regular, Noto Sans Khmer UI Regular, Noto Sans Lao UI Regular, Noto Sans Lepcha Regular, Noto Sans Limbu Regular, Noto Sans Lisu Regular, Noto Sans Malayalam UI Regular, Noto Sans Mandaic Regular, Noto Sans Mongolian Regular, Noto Sans Myanmar UI Regular, Noto Sans New Tai Lue Regular, Noto Sans NKo Regular, Noto Sans Ol Chiki Regular, Noto Sans Oriya UI Regular, Noto Sans Oriya Regular, Noto Sans Osmanya Regular, Noto Sans Samaritan Regular, Noto Sans Saurashtra Regular, Noto Sans Shavian Regular, Noto Sans Sinhala Regular, Noto Sans Sundanese Regular, Noto Sans Symbols Regular, Noto Sans Syriac Eastern Regular, Noto Sans Syriac Estrangela Regular, Noto Sans Syriac Western Regular, Noto Sans Tagalog Regular, Noto Sans Tagbanwa Regular, Noto Sans Tai Le Regular, Noto Sans Tai Tham Regular, Noto Sans Tai Viet Regular, Noto Sans Tamil UI Regular, Noto Sans Telugu UI Regular, Noto Sans Thaana Regular, Noto Sans Thai UI Regular, Noto Sans Tibetan Regular, Noto Sans Tifinagh Regular, Noto Sans Vai Regular, Noto Sans Yi Regular, Noto Naskh Arabic UI Regular, Noto Emoji Regular, DejaVu Sans Book, HanaMinA Regular, HanaMinB Regular, Unifont Medium, unifont Medium, Unifont Upper Medium' (specified as text-face-name) is not a known font on your system, please provide an existing font face name.`

**Comment by Joxit** [comment]
I can not add all these fonts because the docker image will be 155MB bigger (440MB instead of 285MB). These fonts are not a requirement for all carto-projects.
If you need theses fonts, I suggest you download them separately ([see Installation on other operation systems](https://github.com/gravitystorm/openstreetmap-carto/blob/master/INSTALL.md#installation-on-other-operation-systems)) and put them in a fonts folder and use `Map { font-directory: url(./fonts); }` in your mss. Or if fonts are on your computer you can add in the docker option `-v /usr/share/fonts:/usr/share/fonts:ro`

**Comment by randyhbh** [comment]
thanks for your suggestions, i use `-v /usr/share/fonts:/usr/share/fonts:ro` option, work like a charm

**Comment by Joxit** [comment]
You are welcome. I will also add this tip in the README.md
