### ISSUE TITLE
Docker Hub seems to muck up the README.md

### ISSUE THREAD

**Issue by wolfd** [Joxit/docker-kosmtik#4]
<img width="400" alt="screen shot 2019-02-04 at 11 41 11 pm" src="https://user-images.githubusercontent.com/930169/52253531-6c80bf00-28d6-11e9-89be-3003f0c084aa.png">

The example command on docker hub is missing `</opt/project/project.(mml|yml)>` that's in the markdown (which shows up fine on github). As much as I'd like to admit that I figured this out really quickly, it took me an embarrassingly long time.

It looks like Docker Hub is trying to remove xml tags or something? You may want to change the "&lt;" to "&amp;lt;" and "&gt;" to "&amp;gt;"?

**Comment by Joxit** [comment]
Hi, thank you for your issue.
It seems that it was a docker hub issue and it's now fixed (or it's a browser issue ?)
![image](https://user-images.githubusercontent.com/5153882/52378342-b3ea8500-2a67-11e9-9930-6d94b272d7b3.png)

That was a bit strange BTW. If it happens again, I will change the token.
